#   
#   CS 424 Spring 2018 UIC
#   Project 2 - Learning to Fly
#
#   Aaron Struck    - Undergraduate
#   Chris Janowski  - Undergraduate
#   Steve Stranczek - Undergraduate

#
# Import libraries
#

library(shiny)
library(shinydashboard)
library(ggplot2)
library(DT)
library(leaflet)
library(plotly)
library(lubridate)
library(dplyr)

#
# Read in data for January
# 
# For some weird reason, there exists a column called 'X' 
# with no data fields... So remove it via NULL
#
# Verify that flight date is type date and not string
#

januaryFlightData <- read.table(file = "january.csv", sep = ",", header = TRUE)
januaryFlightData$X <- NULL
januaryFlightData$FL_DATE <- as.Date(januaryFlightData$FL_DATE, "%Y-%m-%d")
februaryFlightData <- read.table(file = "february.csv", sep = ",", header = TRUE)
februaryFlightData$X <- NULL
februaryFlightData$FL_DATE <- as.Date(februaryFlightData$FL_DATE, "%Y-%m-%d")
marchFlightData <- read.table(file = "march.csv", sep = ",", header = TRUE)
marchFlightData$X <- NULL
marchFlightData$FL_DATE <- as.Date(marchFlightData$FL_DATE, "%Y-%m-%d")
aprilFlightData <- read.table(file = "april.csv", sep = ",", header = TRUE)
aprilFlightData$X <- NULL
aprilFlightData$FL_DATE <- as.Date(aprilFlightData$FL_DATE, "%Y-%m-%d")
mayFlightData <- read.table(file = "may.csv", sep = ",", header = TRUE)
mayFlightData$X <- NULL
mayFlightData$FL_DATE <- as.Date(mayFlightData$FL_DATE, "%Y-%m-%d")
juneFlightData <- read.table(file = "june.csv", sep = ",", header = TRUE)
juneFlightData$X <- NULL
juneFlightData$FL_DATE <- as.Date(juneFlightData$FL_DATE, "%Y-%m-%d")
julyFlightData <- read.table(file = "july.csv", sep = ",", header = TRUE)
julyFlightData$X <- NULL
julyFlightData$FL_DATE <- as.Date(julyFlightData$FL_DATE, "%Y-%m-%d")
augustFlightData <- read.table(file = "august.csv", sep = ",", header = TRUE)
augustFlightData$X <- NULL
augustFlightData$FL_DATE <- as.Date(augustFlightData$FL_DATE, "%Y-%m-%d")
septemberFlightData <- read.table(file = "september.csv", sep = ",", header = TRUE)
septemberFlightData$X <- NULL
septemberFlightData$FL_DATE <- as.Date(septemberFlightData$FL_DATE, "%Y-%m-%d")
octoberFlightData <- read.table(file = "october.csv", sep = ",", header = TRUE)
octoberFlightData$X <- NULL
octoberFlightData$FL_DATE <- as.Date(octoberFlightData$FL_DATE, "%Y-%m-%d")
novemberFlightData <- read.table(file = "november.csv", sep = ",", header = TRUE)
novemberFlightData$X <- NULL
novemberFlightData$FL_DATE <- as.Date(novemberFlightData$FL_DATE, "%Y-%m-%d")
decemberFlightData <- read.table(file = "december.csv", sep = ",", header = TRUE)
decemberFlightData$X <- NULL
decemberFlightData$FL_DATE <- as.Date(decemberFlightData$FL_DATE, "%Y-%m-%d")

#
# Reformat Departure and Arrival time data
# e.g. 1    to 00:01
# e.g. 533  to 05:33
# e.g. 2232 to 22:32
#

januaryFlightData$DEP_TIME <- sprintf("%04d", januaryFlightData$DEP_TIME)
januaryFlightData$DEP_TIME <- as.POSIXct(januaryFlightData$DEP_TIME,tz="","%H%M")
januaryFlightData$DEP_TIME <- format(januaryFlightData$DEP_TIME, "%H:%M")
januaryFlightData$DEP_TIME12 <- format(strptime(januaryFlightData$DEP_TIME, format='%H:%M'), '%I:%M %p')
januaryFlightData$DEP_HOUR <- hour(ymd_hm(paste(januaryFlightData$FL_DATE, januaryFlightData$DEP_TIME)))

januaryFlightData$ARR_TIME <- sprintf("%04d", januaryFlightData$ARR_TIME)
januaryFlightData$ARR_TIME <- as.POSIXct(januaryFlightData$ARR_TIME,tz="","%H%M")
januaryFlightData$ARR_TIME <- format(januaryFlightData$ARR_TIME, "%H:%M")
januaryFlightData$ARR_TIME12 <- format(strptime(januaryFlightData$ARR_TIME, format='%H:%M'), '%I:%M %p')
januaryFlightData$ARR_HOUR <- hour(ymd_hm(paste(januaryFlightData$FL_DATE, januaryFlightData$ARR_TIME)))

februaryFlightData$DEP_TIME <- sprintf("%04d", februaryFlightData$DEP_TIME)
februaryFlightData$DEP_TIME <- as.POSIXct(februaryFlightData$DEP_TIME,tz="","%H%M")
februaryFlightData$DEP_TIME <- format(februaryFlightData$DEP_TIME, "%H:%M")
februaryFlightData$DEP_TIME12 <- format(strptime(februaryFlightData$DEP_TIME, format='%H:%M'), '%I:%M %p')
februaryFlightData$DEP_HOUR <- hour(ymd_hm(paste(februaryFlightData$FL_DATE, februaryFlightData$DEP_TIME)))

februaryFlightData$ARR_TIME <- sprintf("%04d", februaryFlightData$ARR_TIME)
februaryFlightData$ARR_TIME <- as.POSIXct(februaryFlightData$ARR_TIME,tz="","%H%M")
februaryFlightData$ARR_TIME <- format(februaryFlightData$ARR_TIME, "%H:%M")
februaryFlightData$ARR_TIME12 <- format(strptime(februaryFlightData$ARR_TIME, format='%H:%M'), '%I:%M %p')
februaryFlightData$ARR_HOUR <- hour(ymd_hm(paste(februaryFlightData$FL_DATE, februaryFlightData$ARR_TIME)))

marchFlightData$DEP_TIME <- sprintf("%04d", marchFlightData$DEP_TIME)
marchFlightData$DEP_TIME <- as.POSIXct(marchFlightData$DEP_TIME,tz="","%H%M")
marchFlightData$DEP_TIME <- format(marchFlightData$DEP_TIME, "%H:%M")
marchFlightData$DEP_TIME12 <- format(strptime(marchFlightData$DEP_TIME, format='%H:%M'), '%I:%M %p')
marchFlightData$DEP_HOUR <- hour(ymd_hm(paste(marchFlightData$FL_DATE, marchFlightData$DEP_TIME)))

marchFlightData$ARR_TIME <- sprintf("%04d", marchFlightData$ARR_TIME)
marchFlightData$ARR_TIME <- as.POSIXct(marchFlightData$ARR_TIME,tz="","%H%M")
marchFlightData$ARR_TIME <- format(marchFlightData$ARR_TIME, "%H:%M")
marchFlightData$ARR_TIME12 <- format(strptime(marchFlightData$ARR_TIME, format='%H:%M'), '%I:%M %p')
marchFlightData$ARR_HOUR <- hour(ymd_hm(paste(marchFlightData$FL_DATE, marchFlightData$ARR_TIME)))

aprilFlightData$DEP_TIME <- sprintf("%04d", aprilFlightData$DEP_TIME)
aprilFlightData$DEP_TIME <- as.POSIXct(aprilFlightData$DEP_TIME,tz="","%H%M")
aprilFlightData$DEP_TIME <- format(aprilFlightData$DEP_TIME, "%H:%M")
aprilFlightData$DEP_TIME12 <- format(strptime(aprilFlightData$DEP_TIME, format='%H:%M'), '%I:%M %p')
aprilFlightData$DEP_HOUR <- hour(ymd_hm(paste(aprilFlightData$FL_DATE, aprilFlightData$DEP_TIME)))

aprilFlightData$ARR_TIME <- sprintf("%04d", aprilFlightData$ARR_TIME)
aprilFlightData$ARR_TIME <- as.POSIXct(aprilFlightData$ARR_TIME,tz="","%H%M")
aprilFlightData$ARR_TIME <- format(aprilFlightData$ARR_TIME, "%H:%M")
aprilFlightData$ARR_TIME12 <- format(strptime(aprilFlightData$ARR_TIME, format='%H:%M'), '%I:%M %p')
aprilFlightData$ARR_HOUR <- hour(ymd_hm(paste(aprilFlightData$FL_DATE, aprilFlightData$ARR_TIME)))

mayFlightData$DEP_TIME <- sprintf("%04d", mayFlightData$DEP_TIME)
mayFlightData$DEP_TIME <- as.POSIXct(mayFlightData$DEP_TIME,tz="","%H%M")
mayFlightData$DEP_TIME <- format(mayFlightData$DEP_TIME, "%H:%M")
mayFlightData$DEP_TIME12 <- format(strptime(mayFlightData$DEP_TIME, format='%H:%M'), '%I:%M %p')
mayFlightData$DEP_HOUR <- hour(ymd_hm(paste(aprilFlightData$FL_DATE, mayFlightData$DEP_TIME)))

mayFlightData$ARR_TIME <- sprintf("%04d", mayFlightData$ARR_TIME)
mayFlightData$ARR_TIME <- as.POSIXct(mayFlightData$ARR_TIME,tz="","%H%M")
mayFlightData$ARR_TIME <- format(mayFlightData$ARR_TIME, "%H:%M")
mayFlightData$ARR_TIME12 <- format(strptime(mayFlightData$ARR_TIME, format='%H:%M'), '%I:%M %p')
mayFlightData$ARR_HOUR <- hour(ymd_hm(paste(aprilFlightData$FL_DATE, mayFlightData$ARR_TIME)))

juneFlightData$DEP_TIME <- sprintf("%04d", juneFlightData$DEP_TIME)
juneFlightData$DEP_TIME <- as.POSIXct(juneFlightData$DEP_TIME,tz="","%H%M")
juneFlightData$DEP_TIME <- format(juneFlightData$DEP_TIME, "%H:%M")
juneFlightData$DEP_TIME12 <- format(strptime(juneFlightData$DEP_TIME, format='%H:%M'), '%I:%M %p')
juneFlightData$DEP_HOUR <- hour(ymd_hm(paste(juneFlightData$FL_DATE, juneFlightData$DEP_TIME)))

juneFlightData$ARR_TIME <- sprintf("%04d", juneFlightData$ARR_TIME)
juneFlightData$ARR_TIME <- as.POSIXct(juneFlightData$ARR_TIME,tz="","%H%M")
juneFlightData$ARR_TIME <- format(juneFlightData$ARR_TIME, "%H:%M")
juneFlightData$ARR_TIME12 <- format(strptime(juneFlightData$ARR_TIME, format='%H:%M'), '%I:%M %p')
juneFlightData$ARR_HOUR <- hour(ymd_hm(paste(juneFlightData$FL_DATE, juneFlightData$ARR_TIME)))

julyFlightData$DEP_TIME <- sprintf("%04d", julyFlightData$DEP_TIME)
julyFlightData$DEP_TIME <- as.POSIXct(julyFlightData$DEP_TIME,tz="","%H%M")
julyFlightData$DEP_TIME <- format(julyFlightData$DEP_TIME, "%H:%M")
julyFlightData$DEP_TIME12 <- format(strptime(julyFlightData$DEP_TIME, format='%H:%M'), '%I:%M %p')
julyFlightData$DEP_HOUR <- hour(ymd_hm(paste(julyFlightData$FL_DATE, julyFlightData$DEP_TIME)))

julyFlightData$ARR_TIME <- sprintf("%04d", julyFlightData$ARR_TIME)
julyFlightData$ARR_TIME <- as.POSIXct(julyFlightData$ARR_TIME,tz="","%H%M")
julyFlightData$ARR_TIME <- format(julyFlightData$ARR_TIME, "%H:%M")
julyFlightData$ARR_TIME12 <- format(strptime(julyFlightData$ARR_TIME, format='%H:%M'), '%I:%M %p')
julyFlightData$ARR_HOUR <- hour(ymd_hm(paste(julyFlightData$FL_DATE, julyFlightData$ARR_TIME)))

augustFlightData$DEP_TIME <- sprintf("%04d", augustFlightData$DEP_TIME)
augustFlightData$DEP_TIME <- as.POSIXct(augustFlightData$DEP_TIME,tz="","%H%M")
augustFlightData$DEP_TIME <- format(augustFlightData$DEP_TIME, "%H:%M")
augustFlightData$DEP_TIME12 <- format(strptime(augustFlightData$DEP_TIME, format='%H:%M'), '%I:%M %p')
augustFlightData$DEP_HOUR <- hour(ymd_hm(paste(augustFlightData$FL_DATE, augustFlightData$DEP_TIME)))

augustFlightData$ARR_TIME <- sprintf("%04d", augustFlightData$ARR_TIME)
augustFlightData$ARR_TIME <- as.POSIXct(augustFlightData$ARR_TIME,tz="","%H%M")
augustFlightData$ARR_TIME <- format(augustFlightData$ARR_TIME, "%H:%M")
augustFlightData$ARR_TIME12 <- format(strptime(augustFlightData$ARR_TIME, format='%H:%M'), '%I:%M %p')
augustFlightData$ARR_HOUR <- hour(ymd_hm(paste(augustFlightData$FL_DATE, augustFlightData$ARR_TIME)))

septemberFlightData$DEP_TIME <- sprintf("%04d", septemberFlightData$DEP_TIME)
septemberFlightData$DEP_TIME <- as.POSIXct(septemberFlightData$DEP_TIME,tz="","%H%M")
septemberFlightData$DEP_TIME <- format(septemberFlightData$DEP_TIME, "%H:%M")
septemberFlightData$DEP_TIME12 <- format(strptime(septemberFlightData$DEP_TIME, format='%H:%M'), '%I:%M %p')
septemberFlightData$DEP_HOUR <- hour(ymd_hm(paste(septemberFlightData$FL_DATE, septemberFlightData$DEP_TIME)))

septemberFlightData$ARR_TIME <- sprintf("%04d", septemberFlightData$ARR_TIME)
septemberFlightData$ARR_TIME <- as.POSIXct(septemberFlightData$ARR_TIME,tz="","%H%M")
septemberFlightData$ARR_TIME <- format(septemberFlightData$ARR_TIME, "%H:%M")
septemberFlightData$ARR_TIME12 <- format(strptime(septemberFlightData$ARR_TIME, format='%H:%M'), '%I:%M %p')
septemberFlightData$ARR_HOUR <- hour(ymd_hm(paste(septemberFlightData$FL_DATE, septemberFlightData$ARR_TIME)))

octoberFlightData$DEP_TIME <- sprintf("%04d", octoberFlightData$DEP_TIME)
octoberFlightData$DEP_TIME <- as.POSIXct(octoberFlightData$DEP_TIME,tz="","%H%M")
octoberFlightData$DEP_TIME <- format(octoberFlightData$DEP_TIME, "%H:%M")
octoberFlightData$DEP_TIME12 <- format(strptime(octoberFlightData$DEP_TIME, format='%H:%M'), '%I:%M %p')
octoberFlightData$DEP_HOUR <- hour(ymd_hm(paste(octoberFlightData$FL_DATE, octoberFlightData$DEP_TIME)))

octoberFlightData$ARR_TIME <- sprintf("%04d", octoberFlightData$ARR_TIME)
octoberFlightData$ARR_TIME <- as.POSIXct(octoberFlightData$ARR_TIME,tz="","%H%M")
octoberFlightData$ARR_TIME <- format(octoberFlightData$ARR_TIME, "%H:%M")
octoberFlightData$ARR_TIME12 <- format(strptime(octoberFlightData$ARR_TIME, format='%H:%M'), '%I:%M %p')
octoberFlightData$ARR_HOUR <- hour(ymd_hm(paste(octoberFlightData$FL_DATE, octoberFlightData$ARR_TIME)))

novemberFlightData$DEP_TIME <- sprintf("%04d", novemberFlightData$DEP_TIME)
novemberFlightData$DEP_TIME <- as.POSIXct(novemberFlightData$DEP_TIME,tz="","%H%M")
novemberFlightData$DEP_TIME <- format(novemberFlightData$DEP_TIME, "%H:%M")
novemberFlightData$DEP_TIME12 <- format(strptime(novemberFlightData$DEP_TIME, format='%H:%M'), '%I:%M %p')
novemberFlightData$DEP_HOUR <- hour(ymd_hm(paste(novemberFlightData$FL_DATE, novemberFlightData$DEP_TIME)))

novemberFlightData$ARR_TIME <- sprintf("%04d", novemberFlightData$ARR_TIME)
novemberFlightData$ARR_TIME <- as.POSIXct(novemberFlightData$ARR_TIME,tz="","%H%M")
novemberFlightData$ARR_TIME <- format(novemberFlightData$ARR_TIME, "%H:%M")
novemberFlightData$ARR_TIME12 <- format(strptime(novemberFlightData$ARR_TIME, format='%H:%M'), '%I:%M %p')
novemberFlightData$ARR_HOUR <- hour(ymd_hm(paste(novemberFlightData$FL_DATE, novemberFlightData$ARR_TIME)))

decemberFlightData$DEP_TIME <- sprintf("%04d", decemberFlightData$DEP_TIME)
decemberFlightData$DEP_TIME <- as.POSIXct(decemberFlightData$DEP_TIME,tz="","%H%M")
decemberFlightData$DEP_TIME <- format(decemberFlightData$DEP_TIME, "%H:%M")
decemberFlightData$DEP_TIME12 <- format(strptime(decemberFlightData$DEP_TIME, format='%H:%M'), '%I:%M %p')
decemberFlightData$DEP_HOUR <- hour(ymd_hm(paste(decemberFlightData$FL_DATE, decemberFlightData$DEP_TIME)))

decemberFlightData$ARR_TIME <- sprintf("%04d", decemberFlightData$ARR_TIME)
decemberFlightData$ARR_TIME <- as.POSIXct(decemberFlightData$ARR_TIME,tz="","%H%M")
decemberFlightData$ARR_TIME <- format(decemberFlightData$ARR_TIME, "%H:%M")
decemberFlightData$ARR_TIME12 <- format(strptime(decemberFlightData$ARR_TIME, format='%H:%M'), '%I:%M %p')
decemberFlightData$ARR_HOUR <- hour(ymd_hm(paste(decemberFlightData$FL_DATE, decemberFlightData$ARR_TIME)))

#
# NOTE: Airport IDs
#   - Midway = 13232
#   - O'Hare = 13930
#

# Get subsets for midway and o'hare
midwayDest <- subset(januaryFlightData, januaryFlightData$DEST_AIRPORT_ID == "13232")
midwayOrigin <- subset(januaryFlightData, januaryFlightData$ORIGIN_AIRPORT_ID == "13232")

ohareDest <- subset(januaryFlightData, januaryFlightData$DEST_AIRPORT_ID == "13930")
ohareOrigin <- subset(januaryFlightData, januaryFlightData$ORIGIN_AIRPORT_ID == "13930")

#
# Get list and counts of all unique airlines in midway
# and o'hare, then do some column reformatting
#
# Arrival = Dest, Departure = Origin
#
ohareAirlines <- as.data.frame(table(ohareDest$CARRIER))
colnames(ohareAirlines)[colnames(ohareAirlines) == "Var1"] <- "Carrier"
colnames(ohareAirlines)[colnames(ohareAirlines) == "Freq"] <- "Arrivals"
ohareAirlines$Departures <- table(ohareOrigin$CARRIER)

midwayAirlines <- as.data.frame(table(midwayDest$CARRIER))
colnames(midwayAirlines)[colnames(midwayAirlines) == "Var1"] <- "Carrier"
colnames(midwayAirlines)[colnames(midwayAirlines) == "Freq"] <- "Arrivals"
midwayAirlines$Departures <- table(midwayOrigin$CARRIER)


# Get total arrivals and departures for each airport
midwayDestTotal <- nrow(midwayDest)
midwayOriginTotal <- nrow(midwayOrigin)

ohareDestTotal <- nrow(ohareDest)
ohareOriginTotal <- nrow(ohareOrigin)

# Get each day of the week for ohare
ohareDestMonday <- subset(ohareDest, weekdays(as.Date(ohareDest$FL_DATE,"%Y-%m-%d")) == "Monday")
ohareOriginMonday <- subset(ohareOrigin, weekdays(as.Date(ohareOrigin$FL_DATE,"%Y-%m-%d")) == "Monday")

ohareDestTuesday <- subset(ohareDest, weekdays(as.Date(ohareDest$FL_DATE,"%Y-%m-%d")) == "Tuesday")
ohareOriginTuesday <- subset(ohareOrigin, weekdays(as.Date(ohareOrigin$FL_DATE,"%Y-%m-%d")) == "Tuesday")

ohareDestWednesday <- subset(ohareDest, weekdays(as.Date(ohareDest$FL_DATE,"%Y-%m-%d")) == "Wednesday")
ohareOriginWednesday <- subset(ohareOrigin, weekdays(as.Date(ohareOrigin$FL_DATE,"%Y-%m-%d")) == "Wednesday")

ohareDestThursday <- subset(ohareDest, weekdays(as.Date(ohareDest$FL_DATE,"%Y-%m-%d")) == "Thursday")
ohareOriginThursday <- subset(ohareOrigin, weekdays(as.Date(ohareOrigin$FL_DATE,"%Y-%m-%d")) == "Thursday")

ohareDestFriday <- subset(ohareDest, weekdays(as.Date(ohareDest$FL_DATE,"%Y-%m-%d")) == "Friday")
ohareOriginFriday <- subset(ohareOrigin, weekdays(as.Date(ohareOrigin$FL_DATE,"%Y-%m-%d")) == "Friday")

ohareDestSaturday <- subset(ohareDest, weekdays(as.Date(ohareDest$FL_DATE,"%Y-%m-%d")) == "Saturday")
ohareOriginSaturday <- subset(ohareOrigin, weekdays(as.Date(ohareOrigin$FL_DATE,"%Y-%m-%d")) == "Saturday")

ohareDestSunday <- subset(ohareDest, weekdays(as.Date(ohareDest$FL_DATE,"%Y-%m-%d")) == "Sunday")
ohareOriginSunday <- subset(ohareOrigin, weekdays(as.Date(ohareOrigin$FL_DATE,"%Y-%m-%d")) == "Sunday")

# Midway
midwayDestMonday <- subset(midwayDest, weekdays(as.Date(midwayDest$FL_DATE,"%Y-%m-%d")) == "Monday")
midwayOriginMonday <- subset(midwayOrigin, weekdays(as.Date(midwayOrigin$FL_DATE,"%Y-%m-%d")) == "Monday")

midwayDestTuesday <- subset(midwayDest, weekdays(as.Date(midwayDest$FL_DATE,"%Y-%m-%d")) == "Tuesday")
midwayOriginTuesday <- subset(midwayOrigin, weekdays(as.Date(midwayOrigin$FL_DATE,"%Y-%m-%d")) == "Tuesday")

midwayDestWednesday <- subset(midwayDest, weekdays(as.Date(midwayDest$FL_DATE,"%Y-%m-%d")) == "Wednesday")
midwayOriginWednesday <- subset(midwayOrigin, weekdays(as.Date(midwayOrigin$FL_DATE,"%Y-%m-%d")) == "Wednesday")

midwayDestThursday <- subset(midwayDest, weekdays(as.Date(midwayDest$FL_DATE,"%Y-%m-%d")) == "Thursday")
midwayOriginThursday <- subset(midwayOrigin, weekdays(as.Date(midwayOrigin$FL_DATE,"%Y-%m-%d")) == "Thursday")

midwayDestFriday <- subset(midwayDest, weekdays(as.Date(midwayDest$FL_DATE,"%Y-%m-%d")) == "Friday")
midwayOriginFriday <- subset(midwayOrigin, weekdays(as.Date(midwayOrigin$FL_DATE,"%Y-%m-%d")) == "Friday")

midwayDestSaturday <- subset(midwayDest, weekdays(as.Date(midwayDest$FL_DATE,"%Y-%m-%d")) == "Saturday")
midwayOriginSaturday <- subset(midwayOrigin, weekdays(as.Date(midwayOrigin$FL_DATE,"%Y-%m-%d")) == "Saturday")

midwayDestSunday <- subset(midwayDest, weekdays(as.Date(midwayDest$FL_DATE,"%Y-%m-%d")) == "Sunday")
midwayOriginSunday <- subset(midwayOrigin, weekdays(as.Date(midwayOrigin$FL_DATE,"%Y-%m-%d")) == "Sunday")

# Create single file for both ohare and midway to encapsulate days of week for ohare
ohareDayData <- data.frame(matrix(ncol = 3, nrow = 0))
x <- c("Day", "Departures", "Arrivals")
colnames(ohareDayData) <- x

midwayDayData <- data.frame(matrix(ncol = 3, nrow = 0))
x <- c("Day", "Departures", "Arrivals")
colnames(midwayDayData) <- x

tempArr <- nrow(ohareDestMonday)
tempDep  <- nrow(ohareOriginMonday)
ohareDayData[nrow(ohareDayData) + 1, ] <- c( "Monday", tempDep,tempArr)

tempArr <- nrow(ohareDestTuesday)
tempDep  <- nrow(ohareOriginTuesday)
ohareDayData[nrow(ohareDayData) + 1, ] <- c( "Tuesday", tempDep,tempArr)

tempArr <- nrow(ohareDestWednesday)
tempDep  <- nrow(ohareOriginWednesday)
ohareDayData[nrow(ohareDayData) + 1, ] <- c( "Wednesday", tempDep,tempArr)

tempArr <- nrow(ohareDestThursday)
tempDep  <- nrow(ohareOriginThursday)
ohareDayData[nrow(ohareDayData) + 1, ] <- c( "Thursday", tempDep,tempArr)

tempArr <- nrow(ohareDestFriday)
tempDep  <- nrow(ohareOriginFriday)
ohareDayData[nrow(ohareDayData) + 1, ] <- c( "Friday", tempDep,tempArr)

tempArr <- nrow(ohareDestSaturday)
tempDep  <- nrow(ohareOriginSaturday)
ohareDayData[nrow(ohareDayData) + 1, ] <- c( "Saturday", tempDep,tempArr)

tempArr <- nrow(ohareDestSunday)
tempDep  <- nrow(ohareOriginSunday)
ohareDayData[nrow(ohareDayData) + 1, ] <- c( "Sunday", tempDep,tempArr)

# Midway day data
tempArr <- nrow(midwayDestMonday)
tempDep  <- nrow(midwayOriginMonday)
midwayDayData[nrow(midwayDayData) + 1, ] <- c( "Monday", tempDep,tempArr)

tempArr <- nrow(midwayDestTuesday)
tempDep  <- nrow(midwayOriginTuesday)
midwayDayData[nrow(midwayDayData) + 1, ] <- c( "Tuesday", tempDep,tempArr)

tempArr <- nrow(midwayDestWednesday)
tempDep  <- nrow(midwayOriginWednesday)
midwayDayData[nrow(midwayDayData) + 1, ] <- c( "Wednesday", tempDep,tempArr)

tempArr <- nrow(midwayDestThursday)
tempDep  <- nrow(midwayOriginThursday)
midwayDayData[nrow(midwayDayData) + 1, ] <- c( "Thursday", tempDep,tempArr)

tempArr <- nrow(midwayDestFriday)
tempDep  <- nrow(midwayOriginFriday)
midwayDayData[nrow(midwayDayData) + 1, ] <- c( "Friday", tempDep,tempArr)

tempArr <- nrow(midwayDestSaturday)
tempDep  <- nrow(midwayOriginSaturday)
midwayDayData[nrow(midwayDayData) + 1, ] <- c( "Saturday", tempDep,tempArr)

tempArr <- nrow(midwayDestSunday)
tempDep  <- nrow(midwayOriginSunday)
midwayDayData[nrow(midwayDayData) + 1, ] <- c( "Sunday", tempDep,tempArr)

#Delay Sum Data
janDelayTemp <- c()
janDelay <- c()
janDelayTemp$hour0<-subset(januaryFlightData, DEP_HOUR==0)
janDelayTemp$hour1<-subset(januaryFlightData, DEP_HOUR==1)
janDelayTemp$hour2<-subset(januaryFlightData, DEP_HOUR==2)
janDelayTemp$hour3<-subset(januaryFlightData, DEP_HOUR==3)
janDelayTemp$hour4<-subset(januaryFlightData, DEP_HOUR==4)
janDelayTemp$hour5<-subset(januaryFlightData, DEP_HOUR==5)
janDelayTemp$hour6<-subset(januaryFlightData, DEP_HOUR==6)
janDelayTemp$hour7<-subset(januaryFlightData, DEP_HOUR==7)
janDelayTemp$hour8<-subset(januaryFlightData, DEP_HOUR==8)
janDelayTemp$hour9<-subset(januaryFlightData, DEP_HOUR==9)
janDelayTemp$hour10<-subset(januaryFlightData, DEP_HOUR==10)
janDelayTemp$hour11<-subset(januaryFlightData, DEP_HOUR==11)
janDelayTemp$hour12<-subset(januaryFlightData, DEP_HOUR==12)
janDelayTemp$hour13<-subset(januaryFlightData, DEP_HOUR==13)
janDelayTemp$hour14<-subset(januaryFlightData, DEP_HOUR==14)
janDelayTemp$hour15<-subset(januaryFlightData, DEP_HOUR==15)
janDelayTemp$hour16<-subset(januaryFlightData, DEP_HOUR==16)
janDelayTemp$hour17<-subset(januaryFlightData, DEP_HOUR==17)
janDelayTemp$hour18<-subset(januaryFlightData, DEP_HOUR==18)
janDelayTemp$hour19<-subset(januaryFlightData, DEP_HOUR==19)
janDelayTemp$hour20<-subset(januaryFlightData, DEP_HOUR==20)
janDelayTemp$hour21<-subset(januaryFlightData, DEP_HOUR==21)
janDelayTemp$hour22<-subset(januaryFlightData, DEP_HOUR==22)
janDelayTemp$hour23<-subset(januaryFlightData, DEP_HOUR==23)
janDelay$hour0 <- sum(janDelayTemp$hour0$CANCELLED)
janDelay$hour1 <- sum(janDelayTemp$hour1$CANCELLED)
janDelay$hour2 <- sum(janDelayTemp$hour2$CANCELLED)
janDelay$hour3 <- sum(janDelayTemp$hour3$CANCELLED)
janDelay$hour4 <- sum(janDelayTemp$hour4$CANCELLED)
janDelay$hour5 <- sum(janDelayTemp$hour5$CANCELLED)
janDelay$hour6 <- sum(janDelayTemp$hour6$CANCELLED)
janDelay$hour7 <- sum(janDelayTemp$hour7$CANCELLED)
janDelay$hour8 <- sum(janDelayTemp$hour8$CANCELLED)
janDelay$hour9 <- sum(janDelayTemp$hour9$CANCELLED)
janDelay$hour10 <- sum(janDelayTemp$hour10$CANCELLED)
janDelay$hour11 <- sum(janDelayTemp$hour11$CANCELLED)
janDelay$hour12 <- sum(janDelayTemp$hour12$CANCELLED)
janDelay$hour13 <- sum(janDelayTemp$hour13$CANCELLED)
janDelay$hour14 <- sum(janDelayTemp$hour14$CANCELLED)
janDelay$hour15 <- sum(janDelayTemp$hour15$CANCELLED)
janDelay$hour16 <- sum(janDelayTemp$hour16$CANCELLED)
janDelay$hour17 <- sum(janDelayTemp$hour17$CANCELLED)
janDelay$hour18 <- sum(janDelayTemp$hour18$CANCELLED)
janDelay$hour19 <- sum(janDelayTemp$hour19$CANCELLED)
janDelay$hour20 <- sum(janDelayTemp$hour20$CANCELLED)
janDelay$hour21 <- sum(janDelayTemp$hour21$CANCELLED)
janDelay$hour22 <- sum(janDelayTemp$hour22$CANCELLED)
janDelay$hour23 <- sum(janDelayTemp$hour23$CANCELLED)
febDelayTemp <- c()
febDelay <- c()
febDelayTemp$hour0<-subset(februaryFlightData, DEP_HOUR==0)
febDelayTemp$hour1<-subset(februaryFlightData, DEP_HOUR==1)
febDelayTemp$hour2<-subset(februaryFlightData, DEP_HOUR==2)
febDelayTemp$hour3<-subset(februaryFlightData, DEP_HOUR==3)
febDelayTemp$hour4<-subset(februaryFlightData, DEP_HOUR==4)
febDelayTemp$hour5<-subset(februaryFlightData, DEP_HOUR==5)
febDelayTemp$hour6<-subset(februaryFlightData, DEP_HOUR==6)
febDelayTemp$hour7<-subset(februaryFlightData, DEP_HOUR==7)
febDelayTemp$hour8<-subset(februaryFlightData, DEP_HOUR==8)
febDelayTemp$hour9<-subset(februaryFlightData, DEP_HOUR==9)
febDelayTemp$hour10<-subset(februaryFlightData, DEP_HOUR==10)
febDelayTemp$hour11<-subset(februaryFlightData, DEP_HOUR==11)
febDelayTemp$hour12<-subset(februaryFlightData, DEP_HOUR==12)
febDelayTemp$hour13<-subset(februaryFlightData, DEP_HOUR==13)
febDelayTemp$hour14<-subset(februaryFlightData, DEP_HOUR==14)
febDelayTemp$hour15<-subset(februaryFlightData, DEP_HOUR==15)
febDelayTemp$hour16<-subset(februaryFlightData, DEP_HOUR==16)
febDelayTemp$hour17<-subset(februaryFlightData, DEP_HOUR==17)
febDelayTemp$hour18<-subset(februaryFlightData, DEP_HOUR==18)
febDelayTemp$hour19<-subset(februaryFlightData, DEP_HOUR==19)
febDelayTemp$hour20<-subset(februaryFlightData, DEP_HOUR==20)
febDelayTemp$hour21<-subset(februaryFlightData, DEP_HOUR==21)
febDelayTemp$hour22<-subset(februaryFlightData, DEP_HOUR==22)
febDelayTemp$hour23<-subset(februaryFlightData, DEP_HOUR==23)
febDelay$hour0 <- sum(febDelayTemp$hour0$CANCELLED)
febDelay$hour1 <- sum(febDelayTemp$hour1$CANCELLED)
febDelay$hour2 <- sum(febDelayTemp$hour2$CANCELLED)
febDelay$hour3 <- sum(febDelayTemp$hour3$CANCELLED)
febDelay$hour4 <- sum(febDelayTemp$hour4$CANCELLED)
febDelay$hour5 <- sum(febDelayTemp$hour5$CANCELLED)
febDelay$hour6 <- sum(febDelayTemp$hour6$CANCELLED)
febDelay$hour7 <- sum(febDelayTemp$hour7$CANCELLED)
febDelay$hour8 <- sum(febDelayTemp$hour8$CANCELLED)
febDelay$hour9 <- sum(febDelayTemp$hour9$CANCELLED)
febDelay$hour10 <- sum(febDelayTemp$hour10$CANCELLED)
febDelay$hour11 <- sum(febDelayTemp$hour11$CANCELLED)
febDelay$hour12 <- sum(febDelayTemp$hour12$CANCELLED)
febDelay$hour13 <- sum(febDelayTemp$hour13$CANCELLED)
febDelay$hour14 <- sum(febDelayTemp$hour14$CANCELLED)
febDelay$hour15 <- sum(febDelayTemp$hour15$CANCELLED)
febDelay$hour16 <- sum(febDelayTemp$hour16$CANCELLED)
febDelay$hour17 <- sum(febDelayTemp$hour17$CANCELLED)
febDelay$hour18 <- sum(febDelayTemp$hour18$CANCELLED)
febDelay$hour19 <- sum(febDelayTemp$hour19$CANCELLED)
febDelay$hour20 <- sum(febDelayTemp$hour20$CANCELLED)
febDelay$hour21 <- sum(febDelayTemp$hour21$CANCELLED)
febDelay$hour22 <- sum(febDelayTemp$hour22$CANCELLED)
febDelay$hour23 <- sum(febDelayTemp$hour23$CANCELLED)
marDelayTemp <- c()
marDelay <- c()
marDelayTemp$hour0<-subset(marchFlightData, DEP_HOUR==0)
marDelayTemp$hour1<-subset(marchFlightData, DEP_HOUR==1)
marDelayTemp$hour2<-subset(marchFlightData, DEP_HOUR==2)
marDelayTemp$hour3<-subset(marchFlightData, DEP_HOUR==3)
marDelayTemp$hour4<-subset(marchFlightData, DEP_HOUR==4)
marDelayTemp$hour5<-subset(marchFlightData, DEP_HOUR==5)
marDelayTemp$hour6<-subset(marchFlightData, DEP_HOUR==6)
marDelayTemp$hour7<-subset(marchFlightData, DEP_HOUR==7)
marDelayTemp$hour8<-subset(marchFlightData, DEP_HOUR==8)
marDelayTemp$hour9<-subset(marchFlightData, DEP_HOUR==9)
marDelayTemp$hour10<-subset(marchFlightData, DEP_HOUR==10)
marDelayTemp$hour11<-subset(marchFlightData, DEP_HOUR==11)
marDelayTemp$hour12<-subset(marchFlightData, DEP_HOUR==12)
marDelayTemp$hour13<-subset(marchFlightData, DEP_HOUR==13)
marDelayTemp$hour14<-subset(marchFlightData, DEP_HOUR==14)
marDelayTemp$hour15<-subset(marchFlightData, DEP_HOUR==15)
marDelayTemp$hour16<-subset(marchFlightData, DEP_HOUR==16)
marDelayTemp$hour17<-subset(marchFlightData, DEP_HOUR==17)
marDelayTemp$hour18<-subset(marchFlightData, DEP_HOUR==18)
marDelayTemp$hour19<-subset(marchFlightData, DEP_HOUR==19)
marDelayTemp$hour20<-subset(marchFlightData, DEP_HOUR==20)
marDelayTemp$hour21<-subset(marchFlightData, DEP_HOUR==21)
marDelayTemp$hour22<-subset(marchFlightData, DEP_HOUR==22)
marDelayTemp$hour23<-subset(marchFlightData, DEP_HOUR==23)
marDelay$hour0 <- sum(marDelayTemp$hour0$CANCELLED)
marDelay$hour1 <- sum(marDelayTemp$hour1$CANCELLED)
marDelay$hour2 <- sum(marDelayTemp$hour2$CANCELLED)
marDelay$hour3 <- sum(marDelayTemp$hour3$CANCELLED)
marDelay$hour4 <- sum(marDelayTemp$hour4$CANCELLED)
marDelay$hour5 <- sum(marDelayTemp$hour5$CANCELLED)
marDelay$hour6 <- sum(marDelayTemp$hour6$CANCELLED)
marDelay$hour7 <- sum(marDelayTemp$hour7$CANCELLED)
marDelay$hour8 <- sum(marDelayTemp$hour8$CANCELLED)
marDelay$hour9 <- sum(marDelayTemp$hour9$CANCELLED)
marDelay$hour10 <- sum(marDelayTemp$hour10$CANCELLED)
marDelay$hour11 <- sum(marDelayTemp$hour11$CANCELLED)
marDelay$hour12 <- sum(marDelayTemp$hour12$CANCELLED)
marDelay$hour13 <- sum(marDelayTemp$hour13$CANCELLED)
marDelay$hour14 <- sum(marDelayTemp$hour14$CANCELLED)
marDelay$hour15 <- sum(marDelayTemp$hour15$CANCELLED)
marDelay$hour16 <- sum(marDelayTemp$hour16$CANCELLED)
marDelay$hour17 <- sum(marDelayTemp$hour17$CANCELLED)
marDelay$hour18 <- sum(marDelayTemp$hour18$CANCELLED)
marDelay$hour19 <- sum(marDelayTemp$hour19$CANCELLED)
marDelay$hour20 <- sum(marDelayTemp$hour20$CANCELLED)
marDelay$hour21 <- sum(marDelayTemp$hour21$CANCELLED)
marDelay$hour22 <- sum(marDelayTemp$hour22$CANCELLED)
marDelay$hour23 <- sum(marDelayTemp$hour23$CANCELLED)
aprDelayTemp <- c()
aprDelay <- c()
aprDelayTemp$hour0<-subset(aprilFlightData, DEP_HOUR==0)
aprDelayTemp$hour1<-subset(aprilFlightData, DEP_HOUR==1)
aprDelayTemp$hour2<-subset(aprilFlightData, DEP_HOUR==2)
aprDelayTemp$hour3<-subset(aprilFlightData, DEP_HOUR==3)
aprDelayTemp$hour4<-subset(aprilFlightData, DEP_HOUR==4)
aprDelayTemp$hour5<-subset(aprilFlightData, DEP_HOUR==5)
aprDelayTemp$hour6<-subset(aprilFlightData, DEP_HOUR==6)
aprDelayTemp$hour7<-subset(aprilFlightData, DEP_HOUR==7)
aprDelayTemp$hour8<-subset(aprilFlightData, DEP_HOUR==8)
aprDelayTemp$hour9<-subset(aprilFlightData, DEP_HOUR==9)
aprDelayTemp$hour10<-subset(aprilFlightData, DEP_HOUR==10)
aprDelayTemp$hour11<-subset(aprilFlightData, DEP_HOUR==11)
aprDelayTemp$hour12<-subset(aprilFlightData, DEP_HOUR==12)
aprDelayTemp$hour13<-subset(aprilFlightData, DEP_HOUR==13)
aprDelayTemp$hour14<-subset(aprilFlightData, DEP_HOUR==14)
aprDelayTemp$hour15<-subset(aprilFlightData, DEP_HOUR==15)
aprDelayTemp$hour16<-subset(aprilFlightData, DEP_HOUR==16)
aprDelayTemp$hour17<-subset(aprilFlightData, DEP_HOUR==17)
aprDelayTemp$hour18<-subset(aprilFlightData, DEP_HOUR==18)
aprDelayTemp$hour19<-subset(aprilFlightData, DEP_HOUR==19)
aprDelayTemp$hour20<-subset(aprilFlightData, DEP_HOUR==20)
aprDelayTemp$hour21<-subset(aprilFlightData, DEP_HOUR==21)
aprDelayTemp$hour22<-subset(aprilFlightData, DEP_HOUR==22)
aprDelayTemp$hour23<-subset(aprilFlightData, DEP_HOUR==23)
aprDelay$hour0 <- sum(aprDelayTemp$hour0$CANCELLED)
aprDelay$hour1 <- sum(aprDelayTemp$hour1$CANCELLED)
aprDelay$hour2 <- sum(aprDelayTemp$hour2$CANCELLED)
aprDelay$hour3 <- sum(aprDelayTemp$hour3$CANCELLED)
aprDelay$hour4 <- sum(aprDelayTemp$hour4$CANCELLED)
aprDelay$hour5 <- sum(aprDelayTemp$hour5$CANCELLED)
aprDelay$hour6 <- sum(aprDelayTemp$hour6$CANCELLED)
aprDelay$hour7 <- sum(aprDelayTemp$hour7$CANCELLED)
aprDelay$hour8 <- sum(aprDelayTemp$hour8$CANCELLED)
aprDelay$hour9 <- sum(aprDelayTemp$hour9$CANCELLED)
aprDelay$hour10 <- sum(aprDelayTemp$hour10$CANCELLED)
aprDelay$hour11 <- sum(aprDelayTemp$hour11$CANCELLED)
aprDelay$hour12 <- sum(aprDelayTemp$hour12$CANCELLED)
aprDelay$hour13 <- sum(aprDelayTemp$hour13$CANCELLED)
aprDelay$hour14 <- sum(aprDelayTemp$hour14$CANCELLED)
aprDelay$hour15 <- sum(aprDelayTemp$hour15$CANCELLED)
aprDelay$hour16 <- sum(aprDelayTemp$hour16$CANCELLED)
aprDelay$hour17 <- sum(aprDelayTemp$hour17$CANCELLED)
aprDelay$hour18 <- sum(aprDelayTemp$hour18$CANCELLED)
aprDelay$hour19 <- sum(aprDelayTemp$hour19$CANCELLED)
aprDelay$hour20 <- sum(aprDelayTemp$hour20$CANCELLED)
aprDelay$hour21 <- sum(aprDelayTemp$hour21$CANCELLED)
aprDelay$hour22 <- sum(aprDelayTemp$hour22$CANCELLED)
aprDelay$hour23 <- sum(aprDelayTemp$hour23$CANCELLED)
mayDelayTemp <- c()
mayDelay <- c()
mayDelayTemp$hour0<-subset(mayFlightData, DEP_HOUR==0)
mayDelayTemp$hour1<-subset(mayFlightData, DEP_HOUR==1)
mayDelayTemp$hour2<-subset(mayFlightData, DEP_HOUR==2)
mayDelayTemp$hour3<-subset(mayFlightData, DEP_HOUR==3)
mayDelayTemp$hour4<-subset(mayFlightData, DEP_HOUR==4)
mayDelayTemp$hour5<-subset(mayFlightData, DEP_HOUR==5)
mayDelayTemp$hour6<-subset(mayFlightData, DEP_HOUR==6)
mayDelayTemp$hour7<-subset(mayFlightData, DEP_HOUR==7)
mayDelayTemp$hour8<-subset(mayFlightData, DEP_HOUR==8)
mayDelayTemp$hour9<-subset(mayFlightData, DEP_HOUR==9)
mayDelayTemp$hour10<-subset(mayFlightData, DEP_HOUR==10)
mayDelayTemp$hour11<-subset(mayFlightData, DEP_HOUR==11)
mayDelayTemp$hour12<-subset(mayFlightData, DEP_HOUR==12)
mayDelayTemp$hour13<-subset(mayFlightData, DEP_HOUR==13)
mayDelayTemp$hour14<-subset(mayFlightData, DEP_HOUR==14)
mayDelayTemp$hour15<-subset(mayFlightData, DEP_HOUR==15)
mayDelayTemp$hour16<-subset(mayFlightData, DEP_HOUR==16)
mayDelayTemp$hour17<-subset(mayFlightData, DEP_HOUR==17)
mayDelayTemp$hour18<-subset(mayFlightData, DEP_HOUR==18)
mayDelayTemp$hour19<-subset(mayFlightData, DEP_HOUR==19)
mayDelayTemp$hour20<-subset(mayFlightData, DEP_HOUR==20)
mayDelayTemp$hour21<-subset(mayFlightData, DEP_HOUR==21)
mayDelayTemp$hour22<-subset(mayFlightData, DEP_HOUR==22)
mayDelayTemp$hour23<-subset(mayFlightData, DEP_HOUR==23)
mayDelay$hour0 <- sum(mayDelayTemp$hour0$CANCELLED)
mayDelay$hour1 <- sum(mayDelayTemp$hour1$CANCELLED)
mayDelay$hour2 <- sum(mayDelayTemp$hour2$CANCELLED)
mayDelay$hour3 <- sum(mayDelayTemp$hour3$CANCELLED)
mayDelay$hour4 <- sum(mayDelayTemp$hour4$CANCELLED)
mayDelay$hour5 <- sum(mayDelayTemp$hour5$CANCELLED)
mayDelay$hour6 <- sum(mayDelayTemp$hour6$CANCELLED)
mayDelay$hour7 <- sum(mayDelayTemp$hour7$CANCELLED)
mayDelay$hour8 <- sum(mayDelayTemp$hour8$CANCELLED)
mayDelay$hour9 <- sum(mayDelayTemp$hour9$CANCELLED)
mayDelay$hour10 <- sum(mayDelayTemp$hour10$CANCELLED)
mayDelay$hour11 <- sum(mayDelayTemp$hour11$CANCELLED)
mayDelay$hour12 <- sum(mayDelayTemp$hour12$CANCELLED)
mayDelay$hour13 <- sum(mayDelayTemp$hour13$CANCELLED)
mayDelay$hour14 <- sum(mayDelayTemp$hour14$CANCELLED)
mayDelay$hour15 <- sum(mayDelayTemp$hour15$CANCELLED)
mayDelay$hour16 <- sum(mayDelayTemp$hour16$CANCELLED)
mayDelay$hour17 <- sum(mayDelayTemp$hour17$CANCELLED)
mayDelay$hour18 <- sum(mayDelayTemp$hour18$CANCELLED)
mayDelay$hour19 <- sum(mayDelayTemp$hour19$CANCELLED)
mayDelay$hour20 <- sum(mayDelayTemp$hour20$CANCELLED)
mayDelay$hour21 <- sum(mayDelayTemp$hour21$CANCELLED)
mayDelay$hour22 <- sum(mayDelayTemp$hour22$CANCELLED)
mayDelay$hour23 <- sum(mayDelayTemp$hour23$CANCELLED)
junDelayTemp <- c()
junDelay <- c()
junDelayTemp$hour0<-subset(juneFlightData, DEP_HOUR==0)
junDelayTemp$hour1<-subset(juneFlightData, DEP_HOUR==1)
junDelayTemp$hour2<-subset(juneFlightData, DEP_HOUR==2)
junDelayTemp$hour3<-subset(juneFlightData, DEP_HOUR==3)
junDelayTemp$hour4<-subset(juneFlightData, DEP_HOUR==4)
junDelayTemp$hour5<-subset(juneFlightData, DEP_HOUR==5)
junDelayTemp$hour6<-subset(juneFlightData, DEP_HOUR==6)
junDelayTemp$hour7<-subset(juneFlightData, DEP_HOUR==7)
junDelayTemp$hour8<-subset(juneFlightData, DEP_HOUR==8)
junDelayTemp$hour9<-subset(juneFlightData, DEP_HOUR==9)
junDelayTemp$hour10<-subset(juneFlightData, DEP_HOUR==10)
junDelayTemp$hour11<-subset(juneFlightData, DEP_HOUR==11)
junDelayTemp$hour12<-subset(juneFlightData, DEP_HOUR==12)
junDelayTemp$hour13<-subset(juneFlightData, DEP_HOUR==13)
junDelayTemp$hour14<-subset(juneFlightData, DEP_HOUR==14)
junDelayTemp$hour15<-subset(juneFlightData, DEP_HOUR==15)
junDelayTemp$hour16<-subset(juneFlightData, DEP_HOUR==16)
junDelayTemp$hour17<-subset(juneFlightData, DEP_HOUR==17)
junDelayTemp$hour18<-subset(juneFlightData, DEP_HOUR==18)
junDelayTemp$hour19<-subset(juneFlightData, DEP_HOUR==19)
junDelayTemp$hour20<-subset(juneFlightData, DEP_HOUR==20)
junDelayTemp$hour21<-subset(juneFlightData, DEP_HOUR==21)
junDelayTemp$hour22<-subset(juneFlightData, DEP_HOUR==22)
junDelayTemp$hour23<-subset(juneFlightData, DEP_HOUR==23)
junDelay$hour0 <- sum(junDelayTemp$hour0$CANCELLED)
junDelay$hour1 <- sum(junDelayTemp$hour1$CANCELLED)
junDelay$hour2 <- sum(junDelayTemp$hour2$CANCELLED)
junDelay$hour3 <- sum(junDelayTemp$hour3$CANCELLED)
junDelay$hour4 <- sum(junDelayTemp$hour4$CANCELLED)
junDelay$hour5 <- sum(junDelayTemp$hour5$CANCELLED)
junDelay$hour6 <- sum(junDelayTemp$hour6$CANCELLED)
junDelay$hour7 <- sum(junDelayTemp$hour7$CANCELLED)
junDelay$hour8 <- sum(junDelayTemp$hour8$CANCELLED)
junDelay$hour9 <- sum(junDelayTemp$hour9$CANCELLED)
junDelay$hour10 <- sum(junDelayTemp$hour10$CANCELLED)
junDelay$hour11 <- sum(junDelayTemp$hour11$CANCELLED)
junDelay$hour12 <- sum(junDelayTemp$hour12$CANCELLED)
junDelay$hour13 <- sum(junDelayTemp$hour13$CANCELLED)
junDelay$hour14 <- sum(junDelayTemp$hour14$CANCELLED)
junDelay$hour15 <- sum(junDelayTemp$hour15$CANCELLED)
junDelay$hour16 <- sum(junDelayTemp$hour16$CANCELLED)
junDelay$hour17 <- sum(junDelayTemp$hour17$CANCELLED)
junDelay$hour18 <- sum(junDelayTemp$hour18$CANCELLED)
junDelay$hour19 <- sum(junDelayTemp$hour19$CANCELLED)
junDelay$hour20 <- sum(junDelayTemp$hour20$CANCELLED)
junDelay$hour21 <- sum(junDelayTemp$hour21$CANCELLED)
junDelay$hour22 <- sum(junDelayTemp$hour22$CANCELLED)
junDelay$hour23 <- sum(junDelayTemp$hour23$CANCELLED)
julDelayTemp <- c()
julDelay <- c()
julDelayTemp$hour0<-subset(julyFlightData, DEP_HOUR==0)
julDelayTemp$hour1<-subset(julyFlightData, DEP_HOUR==1)
julDelayTemp$hour2<-subset(julyFlightData, DEP_HOUR==2)
julDelayTemp$hour3<-subset(julyFlightData, DEP_HOUR==3)
julDelayTemp$hour4<-subset(julyFlightData, DEP_HOUR==4)
julDelayTemp$hour5<-subset(julyFlightData, DEP_HOUR==5)
julDelayTemp$hour6<-subset(julyFlightData, DEP_HOUR==6)
julDelayTemp$hour7<-subset(julyFlightData, DEP_HOUR==7)
julDelayTemp$hour8<-subset(julyFlightData, DEP_HOUR==8)
julDelayTemp$hour9<-subset(julyFlightData, DEP_HOUR==9)
julDelayTemp$hour10<-subset(julyFlightData, DEP_HOUR==10)
julDelayTemp$hour11<-subset(julyFlightData, DEP_HOUR==11)
julDelayTemp$hour12<-subset(julyFlightData, DEP_HOUR==12)
julDelayTemp$hour13<-subset(julyFlightData, DEP_HOUR==13)
julDelayTemp$hour14<-subset(julyFlightData, DEP_HOUR==14)
julDelayTemp$hour15<-subset(julyFlightData, DEP_HOUR==15)
julDelayTemp$hour16<-subset(julyFlightData, DEP_HOUR==16)
julDelayTemp$hour17<-subset(julyFlightData, DEP_HOUR==17)
julDelayTemp$hour18<-subset(julyFlightData, DEP_HOUR==18)
julDelayTemp$hour19<-subset(julyFlightData, DEP_HOUR==19)
julDelayTemp$hour20<-subset(julyFlightData, DEP_HOUR==20)
julDelayTemp$hour21<-subset(julyFlightData, DEP_HOUR==21)
julDelayTemp$hour22<-subset(julyFlightData, DEP_HOUR==22)
julDelayTemp$hour23<-subset(julyFlightData, DEP_HOUR==23)
julDelay$hour0 <- sum(julDelayTemp$hour0$CANCELLED)
julDelay$hour1 <- sum(julDelayTemp$hour1$CANCELLED)
julDelay$hour2 <- sum(julDelayTemp$hour2$CANCELLED)
julDelay$hour3 <- sum(julDelayTemp$hour3$CANCELLED)
julDelay$hour4 <- sum(julDelayTemp$hour4$CANCELLED)
julDelay$hour5 <- sum(julDelayTemp$hour5$CANCELLED)
julDelay$hour6 <- sum(julDelayTemp$hour6$CANCELLED)
julDelay$hour7 <- sum(julDelayTemp$hour7$CANCELLED)
julDelay$hour8 <- sum(julDelayTemp$hour8$CANCELLED)
julDelay$hour9 <- sum(julDelayTemp$hour9$CANCELLED)
julDelay$hour10 <- sum(julDelayTemp$hour10$CANCELLED)
julDelay$hour11 <- sum(julDelayTemp$hour11$CANCELLED)
julDelay$hour12 <- sum(julDelayTemp$hour12$CANCELLED)
julDelay$hour13 <- sum(julDelayTemp$hour13$CANCELLED)
julDelay$hour14 <- sum(julDelayTemp$hour14$CANCELLED)
julDelay$hour15 <- sum(julDelayTemp$hour15$CANCELLED)
julDelay$hour16 <- sum(julDelayTemp$hour16$CANCELLED)
julDelay$hour17 <- sum(julDelayTemp$hour17$CANCELLED)
julDelay$hour18 <- sum(julDelayTemp$hour18$CANCELLED)
julDelay$hour19 <- sum(julDelayTemp$hour19$CANCELLED)
julDelay$hour20 <- sum(julDelayTemp$hour20$CANCELLED)
julDelay$hour21 <- sum(julDelayTemp$hour21$CANCELLED)
julDelay$hour22 <- sum(julDelayTemp$hour22$CANCELLED)
julDelay$hour23 <- sum(julDelayTemp$hour23$CANCELLED)
augDelayTemp <- c()
augDelay <- c()
augDelayTemp$hour0<-subset(augustFlightData, DEP_HOUR==0)
augDelayTemp$hour1<-subset(augustFlightData, DEP_HOUR==1)
augDelayTemp$hour2<-subset(augustFlightData, DEP_HOUR==2)
augDelayTemp$hour3<-subset(augustFlightData, DEP_HOUR==3)
augDelayTemp$hour4<-subset(augustFlightData, DEP_HOUR==4)
augDelayTemp$hour5<-subset(augustFlightData, DEP_HOUR==5)
augDelayTemp$hour6<-subset(augustFlightData, DEP_HOUR==6)
augDelayTemp$hour7<-subset(augustFlightData, DEP_HOUR==7)
augDelayTemp$hour8<-subset(augustFlightData, DEP_HOUR==8)
augDelayTemp$hour9<-subset(augustFlightData, DEP_HOUR==9)
augDelayTemp$hour10<-subset(augustFlightData, DEP_HOUR==10)
augDelayTemp$hour11<-subset(augustFlightData, DEP_HOUR==11)
augDelayTemp$hour12<-subset(augustFlightData, DEP_HOUR==12)
augDelayTemp$hour13<-subset(augustFlightData, DEP_HOUR==13)
augDelayTemp$hour14<-subset(augustFlightData, DEP_HOUR==14)
augDelayTemp$hour15<-subset(augustFlightData, DEP_HOUR==15)
augDelayTemp$hour16<-subset(augustFlightData, DEP_HOUR==16)
augDelayTemp$hour17<-subset(augustFlightData, DEP_HOUR==17)
augDelayTemp$hour18<-subset(augustFlightData, DEP_HOUR==18)
augDelayTemp$hour19<-subset(augustFlightData, DEP_HOUR==19)
augDelayTemp$hour20<-subset(augustFlightData, DEP_HOUR==20)
augDelayTemp$hour21<-subset(augustFlightData, DEP_HOUR==21)
augDelayTemp$hour22<-subset(augustFlightData, DEP_HOUR==22)
augDelayTemp$hour23<-subset(augustFlightData, DEP_HOUR==23)
augDelay$hour0 <- sum(augDelayTemp$hour0$CANCELLED)
augDelay$hour1 <- sum(augDelayTemp$hour1$CANCELLED)
augDelay$hour2 <- sum(augDelayTemp$hour2$CANCELLED)
augDelay$hour3 <- sum(augDelayTemp$hour3$CANCELLED)
augDelay$hour4 <- sum(augDelayTemp$hour4$CANCELLED)
augDelay$hour5 <- sum(augDelayTemp$hour5$CANCELLED)
augDelay$hour6 <- sum(augDelayTemp$hour6$CANCELLED)
augDelay$hour7 <- sum(augDelayTemp$hour7$CANCELLED)
augDelay$hour8 <- sum(augDelayTemp$hour8$CANCELLED)
augDelay$hour9 <- sum(augDelayTemp$hour9$CANCELLED)
augDelay$hour10 <- sum(augDelayTemp$hour10$CANCELLED)
augDelay$hour11 <- sum(augDelayTemp$hour11$CANCELLED)
augDelay$hour12 <- sum(augDelayTemp$hour12$CANCELLED)
augDelay$hour13 <- sum(augDelayTemp$hour13$CANCELLED)
augDelay$hour14 <- sum(augDelayTemp$hour14$CANCELLED)
augDelay$hour15 <- sum(augDelayTemp$hour15$CANCELLED)
augDelay$hour16 <- sum(augDelayTemp$hour16$CANCELLED)
augDelay$hour17 <- sum(augDelayTemp$hour17$CANCELLED)
augDelay$hour18 <- sum(augDelayTemp$hour18$CANCELLED)
augDelay$hour19 <- sum(augDelayTemp$hour19$CANCELLED)
augDelay$hour20 <- sum(augDelayTemp$hour20$CANCELLED)
augDelay$hour21 <- sum(augDelayTemp$hour21$CANCELLED)
augDelay$hour22 <- sum(augDelayTemp$hour22$CANCELLED)
augDelay$hour23 <- sum(augDelayTemp$hour23$CANCELLED)
sepDelayTemp <- c()
sepDelay <- c()
sepDelayTemp$hour0<-subset(septemberFlightData, DEP_HOUR==0)
sepDelayTemp$hour1<-subset(septemberFlightData, DEP_HOUR==1)
sepDelayTemp$hour2<-subset(septemberFlightData, DEP_HOUR==2)
sepDelayTemp$hour3<-subset(septemberFlightData, DEP_HOUR==3)
sepDelayTemp$hour4<-subset(septemberFlightData, DEP_HOUR==4)
sepDelayTemp$hour5<-subset(septemberFlightData, DEP_HOUR==5)
sepDelayTemp$hour6<-subset(septemberFlightData, DEP_HOUR==6)
sepDelayTemp$hour7<-subset(septemberFlightData, DEP_HOUR==7)
sepDelayTemp$hour8<-subset(septemberFlightData, DEP_HOUR==8)
sepDelayTemp$hour9<-subset(septemberFlightData, DEP_HOUR==9)
sepDelayTemp$hour10<-subset(septemberFlightData, DEP_HOUR==10)
sepDelayTemp$hour11<-subset(septemberFlightData, DEP_HOUR==11)
sepDelayTemp$hour12<-subset(septemberFlightData, DEP_HOUR==12)
sepDelayTemp$hour13<-subset(septemberFlightData, DEP_HOUR==13)
sepDelayTemp$hour14<-subset(septemberFlightData, DEP_HOUR==14)
sepDelayTemp$hour15<-subset(septemberFlightData, DEP_HOUR==15)
sepDelayTemp$hour16<-subset(septemberFlightData, DEP_HOUR==16)
sepDelayTemp$hour17<-subset(septemberFlightData, DEP_HOUR==17)
sepDelayTemp$hour18<-subset(septemberFlightData, DEP_HOUR==18)
sepDelayTemp$hour19<-subset(septemberFlightData, DEP_HOUR==19)
sepDelayTemp$hour20<-subset(septemberFlightData, DEP_HOUR==20)
sepDelayTemp$hour21<-subset(septemberFlightData, DEP_HOUR==21)
sepDelayTemp$hour22<-subset(septemberFlightData, DEP_HOUR==22)
sepDelayTemp$hour23<-subset(septemberFlightData, DEP_HOUR==23)
sepDelay$hour0 <- sum(sepDelayTemp$hour0$CANCELLED)
sepDelay$hour1 <- sum(sepDelayTemp$hour1$CANCELLED)
sepDelay$hour2 <- sum(sepDelayTemp$hour2$CANCELLED)
sepDelay$hour3 <- sum(sepDelayTemp$hour3$CANCELLED)
sepDelay$hour4 <- sum(sepDelayTemp$hour4$CANCELLED)
sepDelay$hour5 <- sum(sepDelayTemp$hour5$CANCELLED)
sepDelay$hour6 <- sum(sepDelayTemp$hour6$CANCELLED)
sepDelay$hour7 <- sum(sepDelayTemp$hour7$CANCELLED)
sepDelay$hour8 <- sum(sepDelayTemp$hour8$CANCELLED)
sepDelay$hour9 <- sum(sepDelayTemp$hour9$CANCELLED)
sepDelay$hour10 <- sum(sepDelayTemp$hour10$CANCELLED)
sepDelay$hour11 <- sum(sepDelayTemp$hour11$CANCELLED)
sepDelay$hour12 <- sum(sepDelayTemp$hour12$CANCELLED)
sepDelay$hour13 <- sum(sepDelayTemp$hour13$CANCELLED)
sepDelay$hour14 <- sum(sepDelayTemp$hour14$CANCELLED)
sepDelay$hour15 <- sum(sepDelayTemp$hour15$CANCELLED)
sepDelay$hour16 <- sum(sepDelayTemp$hour16$CANCELLED)
sepDelay$hour17 <- sum(sepDelayTemp$hour17$CANCELLED)
sepDelay$hour18 <- sum(sepDelayTemp$hour18$CANCELLED)
sepDelay$hour19 <- sum(sepDelayTemp$hour19$CANCELLED)
sepDelay$hour20 <- sum(sepDelayTemp$hour20$CANCELLED)
sepDelay$hour21 <- sum(sepDelayTemp$hour21$CANCELLED)
sepDelay$hour22 <- sum(sepDelayTemp$hour22$CANCELLED)
sepDelay$hour23 <- sum(sepDelayTemp$hour23$CANCELLED)
octDelayTemp <- c()
octDelay <- c()
octDelayTemp$hour0<-subset(octoberFlightData, DEP_HOUR==0)
octDelayTemp$hour1<-subset(octoberFlightData, DEP_HOUR==1)
octDelayTemp$hour2<-subset(octoberFlightData, DEP_HOUR==2)
octDelayTemp$hour3<-subset(octoberFlightData, DEP_HOUR==3)
octDelayTemp$hour4<-subset(octoberFlightData, DEP_HOUR==4)
octDelayTemp$hour5<-subset(octoberFlightData, DEP_HOUR==5)
octDelayTemp$hour6<-subset(octoberFlightData, DEP_HOUR==6)
octDelayTemp$hour7<-subset(octoberFlightData, DEP_HOUR==7)
octDelayTemp$hour8<-subset(octoberFlightData, DEP_HOUR==8)
octDelayTemp$hour9<-subset(octoberFlightData, DEP_HOUR==9)
octDelayTemp$hour10<-subset(octoberFlightData, DEP_HOUR==10)
octDelayTemp$hour11<-subset(octoberFlightData, DEP_HOUR==11)
octDelayTemp$hour12<-subset(octoberFlightData, DEP_HOUR==12)
octDelayTemp$hour13<-subset(octoberFlightData, DEP_HOUR==13)
octDelayTemp$hour14<-subset(octoberFlightData, DEP_HOUR==14)
octDelayTemp$hour15<-subset(octoberFlightData, DEP_HOUR==15)
octDelayTemp$hour16<-subset(octoberFlightData, DEP_HOUR==16)
octDelayTemp$hour17<-subset(octoberFlightData, DEP_HOUR==17)
octDelayTemp$hour18<-subset(octoberFlightData, DEP_HOUR==18)
octDelayTemp$hour19<-subset(octoberFlightData, DEP_HOUR==19)
octDelayTemp$hour20<-subset(octoberFlightData, DEP_HOUR==20)
octDelayTemp$hour21<-subset(octoberFlightData, DEP_HOUR==21)
octDelayTemp$hour22<-subset(octoberFlightData, DEP_HOUR==22)
octDelayTemp$hour23<-subset(octoberFlightData, DEP_HOUR==23)
octDelay$hour0 <- sum(octDelayTemp$hour0$CANCELLED)
octDelay$hour1 <- sum(octDelayTemp$hour1$CANCELLED)
octDelay$hour2 <- sum(octDelayTemp$hour2$CANCELLED)
octDelay$hour3 <- sum(octDelayTemp$hour3$CANCELLED)
octDelay$hour4 <- sum(octDelayTemp$hour4$CANCELLED)
octDelay$hour5 <- sum(octDelayTemp$hour5$CANCELLED)
octDelay$hour6 <- sum(octDelayTemp$hour6$CANCELLED)
octDelay$hour7 <- sum(octDelayTemp$hour7$CANCELLED)
octDelay$hour8 <- sum(octDelayTemp$hour8$CANCELLED)
octDelay$hour9 <- sum(octDelayTemp$hour9$CANCELLED)
octDelay$hour10 <- sum(octDelayTemp$hour10$CANCELLED)
octDelay$hour11 <- sum(octDelayTemp$hour11$CANCELLED)
octDelay$hour12 <- sum(octDelayTemp$hour12$CANCELLED)
octDelay$hour13 <- sum(octDelayTemp$hour13$CANCELLED)
octDelay$hour14 <- sum(octDelayTemp$hour14$CANCELLED)
octDelay$hour15 <- sum(octDelayTemp$hour15$CANCELLED)
octDelay$hour16 <- sum(octDelayTemp$hour16$CANCELLED)
octDelay$hour17 <- sum(octDelayTemp$hour17$CANCELLED)
octDelay$hour18 <- sum(octDelayTemp$hour18$CANCELLED)
octDelay$hour19 <- sum(octDelayTemp$hour19$CANCELLED)
octDelay$hour20 <- sum(octDelayTemp$hour20$CANCELLED)
octDelay$hour21 <- sum(octDelayTemp$hour21$CANCELLED)
octDelay$hour22 <- sum(octDelayTemp$hour22$CANCELLED)
octDelay$hour23 <- sum(octDelayTemp$hour23$CANCELLED)
novDelayTemp <- c()
novDelay <- c()
novDelayTemp$hour0<-subset(novemberFlightData, DEP_HOUR==0)
novDelayTemp$hour1<-subset(novemberFlightData, DEP_HOUR==1)
novDelayTemp$hour2<-subset(novemberFlightData, DEP_HOUR==2)
novDelayTemp$hour3<-subset(novemberFlightData, DEP_HOUR==3)
novDelayTemp$hour4<-subset(novemberFlightData, DEP_HOUR==4)
novDelayTemp$hour5<-subset(novemberFlightData, DEP_HOUR==5)
novDelayTemp$hour6<-subset(novemberFlightData, DEP_HOUR==6)
novDelayTemp$hour7<-subset(novemberFlightData, DEP_HOUR==7)
novDelayTemp$hour8<-subset(novemberFlightData, DEP_HOUR==8)
novDelayTemp$hour9<-subset(novemberFlightData, DEP_HOUR==9)
novDelayTemp$hour10<-subset(novemberFlightData, DEP_HOUR==10)
novDelayTemp$hour11<-subset(novemberFlightData, DEP_HOUR==11)
novDelayTemp$hour12<-subset(novemberFlightData, DEP_HOUR==12)
novDelayTemp$hour13<-subset(novemberFlightData, DEP_HOUR==13)
novDelayTemp$hour14<-subset(novemberFlightData, DEP_HOUR==14)
novDelayTemp$hour15<-subset(novemberFlightData, DEP_HOUR==15)
novDelayTemp$hour16<-subset(novemberFlightData, DEP_HOUR==16)
novDelayTemp$hour17<-subset(novemberFlightData, DEP_HOUR==17)
novDelayTemp$hour18<-subset(novemberFlightData, DEP_HOUR==18)
novDelayTemp$hour19<-subset(novemberFlightData, DEP_HOUR==19)
novDelayTemp$hour20<-subset(novemberFlightData, DEP_HOUR==20)
novDelayTemp$hour21<-subset(novemberFlightData, DEP_HOUR==21)
novDelayTemp$hour22<-subset(novemberFlightData, DEP_HOUR==22)
novDelayTemp$hour23<-subset(novemberFlightData, DEP_HOUR==23)
novDelay$hour0 <- sum(novDelayTemp$hour0$CANCELLED)
novDelay$hour1 <- sum(novDelayTemp$hour1$CANCELLED)
novDelay$hour2 <- sum(novDelayTemp$hour2$CANCELLED)
novDelay$hour3 <- sum(novDelayTemp$hour3$CANCELLED)
novDelay$hour4 <- sum(novDelayTemp$hour4$CANCELLED)
novDelay$hour5 <- sum(novDelayTemp$hour5$CANCELLED)
novDelay$hour6 <- sum(novDelayTemp$hour6$CANCELLED)
novDelay$hour7 <- sum(novDelayTemp$hour7$CANCELLED)
novDelay$hour8 <- sum(novDelayTemp$hour8$CANCELLED)
novDelay$hour9 <- sum(novDelayTemp$hour9$CANCELLED)
novDelay$hour10 <- sum(novDelayTemp$hour10$CANCELLED)
novDelay$hour11 <- sum(novDelayTemp$hour11$CANCELLED)
novDelay$hour12 <- sum(novDelayTemp$hour12$CANCELLED)
novDelay$hour13 <- sum(novDelayTemp$hour13$CANCELLED)
novDelay$hour14 <- sum(novDelayTemp$hour14$CANCELLED)
novDelay$hour15 <- sum(novDelayTemp$hour15$CANCELLED)
novDelay$hour16 <- sum(novDelayTemp$hour16$CANCELLED)
novDelay$hour17 <- sum(novDelayTemp$hour17$CANCELLED)
novDelay$hour18 <- sum(novDelayTemp$hour18$CANCELLED)
novDelay$hour19 <- sum(novDelayTemp$hour19$CANCELLED)
novDelay$hour20 <- sum(novDelayTemp$hour20$CANCELLED)
novDelay$hour21 <- sum(novDelayTemp$hour21$CANCELLED)
novDelay$hour22 <- sum(novDelayTemp$hour22$CANCELLED)
novDelay$hour23 <- sum(novDelayTemp$hour23$CANCELLED)
decDelayTemp <- c()
decDelay <- c()
decDelayTemp$hour0<-subset(decemberFlightData, DEP_HOUR==0)
decDelayTemp$hour1<-subset(decemberFlightData, DEP_HOUR==1)
decDelayTemp$hour2<-subset(decemberFlightData, DEP_HOUR==2)
decDelayTemp$hour3<-subset(decemberFlightData, DEP_HOUR==3)
decDelayTemp$hour4<-subset(decemberFlightData, DEP_HOUR==4)
decDelayTemp$hour5<-subset(decemberFlightData, DEP_HOUR==5)
decDelayTemp$hour6<-subset(decemberFlightData, DEP_HOUR==6)
decDelayTemp$hour7<-subset(decemberFlightData, DEP_HOUR==7)
decDelayTemp$hour8<-subset(decemberFlightData, DEP_HOUR==8)
decDelayTemp$hour9<-subset(decemberFlightData, DEP_HOUR==9)
decDelayTemp$hour10<-subset(decemberFlightData, DEP_HOUR==10)
decDelayTemp$hour11<-subset(decemberFlightData, DEP_HOUR==11)
decDelayTemp$hour12<-subset(decemberFlightData, DEP_HOUR==12)
decDelayTemp$hour13<-subset(decemberFlightData, DEP_HOUR==13)
decDelayTemp$hour14<-subset(decemberFlightData, DEP_HOUR==14)
decDelayTemp$hour15<-subset(decemberFlightData, DEP_HOUR==15)
decDelayTemp$hour16<-subset(decemberFlightData, DEP_HOUR==16)
decDelayTemp$hour17<-subset(decemberFlightData, DEP_HOUR==17)
decDelayTemp$hour18<-subset(decemberFlightData, DEP_HOUR==18)
decDelayTemp$hour19<-subset(decemberFlightData, DEP_HOUR==19)
decDelayTemp$hour20<-subset(decemberFlightData, DEP_HOUR==20)
decDelayTemp$hour21<-subset(decemberFlightData, DEP_HOUR==21)
decDelayTemp$hour22<-subset(decemberFlightData, DEP_HOUR==22)
decDelayTemp$hour23<-subset(decemberFlightData, DEP_HOUR==23)
decDelay$hour0 <- sum(decDelayTemp$hour0$CANCELLED)
decDelay$hour1 <- sum(decDelayTemp$hour1$CANCELLED)
decDelay$hour2 <- sum(decDelayTemp$hour2$CANCELLED)
decDelay$hour3 <- sum(decDelayTemp$hour3$CANCELLED)
decDelay$hour4 <- sum(decDelayTemp$hour4$CANCELLED)
decDelay$hour5 <- sum(decDelayTemp$hour5$CANCELLED)
decDelay$hour6 <- sum(decDelayTemp$hour6$CANCELLED)
decDelay$hour7 <- sum(decDelayTemp$hour7$CANCELLED)
decDelay$hour8 <- sum(decDelayTemp$hour8$CANCELLED)
decDelay$hour9 <- sum(decDelayTemp$hour9$CANCELLED)
decDelay$hour10 <- sum(decDelayTemp$hour10$CANCELLED)
decDelay$hour11 <- sum(decDelayTemp$hour11$CANCELLED)
decDelay$hour12 <- sum(decDelayTemp$hour12$CANCELLED)
decDelay$hour13 <- sum(decDelayTemp$hour13$CANCELLED)
decDelay$hour14 <- sum(decDelayTemp$hour14$CANCELLED)
decDelay$hour15 <- sum(decDelayTemp$hour15$CANCELLED)
decDelay$hour16 <- sum(decDelayTemp$hour16$CANCELLED)
decDelay$hour17 <- sum(decDelayTemp$hour17$CANCELLED)
decDelay$hour18 <- sum(decDelayTemp$hour18$CANCELLED)
decDelay$hour19 <- sum(decDelayTemp$hour19$CANCELLED)
decDelay$hour20 <- sum(decDelayTemp$hour20$CANCELLED)
decDelay$hour21 <- sum(decDelayTemp$hour21$CANCELLED)
decDelay$hour22 <- sum(decDelayTemp$hour22$CANCELLED)
decDelay$hour23 <- sum(decDelayTemp$hour23$CANCELLED)

#
# Shiny Dashboard
#

ui <- dashboardPage(
  # Create header and sidebar
  dashboardHeader(title = "CS 424 - Project 2"),
  
  dashboardSidebar(
    sidebarMenu(
      menuItem("O'Hare", tabName = "ohareTab", icon = icon("plane")),
      menuItem("Midway", tabName = "midwayTab", icon = icon("plane")),
      menuItem("About", tabName = "aboutTab", icon = icon("info"))
    ) #end sidebarMenu
  ), #end dashboardSidebar
  
  dashboardBody(
    tabItems(
      
      tabItem(tabName = "ohareTab", icon=icon("plane"),
              fluidRow( 
                box(title = "O'Hare Airline Data as Table", solidHeader = TRUE, status = "primary", width = 12, dataTableOutput("ohareAirlinesTable")
                )
              ),
              fluidRow(
                box(title = "O'Hare Airline Departure Data as Pie Chart", solidHeader = TRUE, status = "primary", width = 6, plotlyOutput("ohareAirlinesDepartPie")
                ),
                box(title = "O'Hare Airline Arrival Data as Pie Chart", solidHeader = TRUE, status = "primary", width = 6, plotlyOutput("ohareAirlinesArrivePie")
                )
              ),
              fluidRow(
                box(title = "O'Hare Day Airline Data as Table", solidHeader = TRUE, status = "primary", width = 12, dataTableOutput("ohareDayDataTable")
                )
              )
            ),
      
      tabItem(tabName = "midwayTab", icon=icon("plane"),
              fluidRow(
                box(title = "Midway Airline Data as Table", solidHeader = TRUE, status = "primary", width = 12, dataTableOutput("midwayAirlinesTable")
                )
              ),
              fluidRow(
                  box(title = "Midway Airline Departure Data as Pie Chart", solidHeader = TRUE, status = "primary", width = 6, plotlyOutput("midwayAirlinesDepartPie")
                  ),
                  box(title = "Midway Airline Arrival Data as Pie Chart", solidHeader = TRUE, status = "primary", width = 6, plotlyOutput("midwayAirlinesArrivePie")
                  )
              ),
              fluidRow(
                box(title = "Midway Day Airline Data as Table", solidHeader = TRUE, status = "primary", width = 12, dataTableOutput("midwayDayDataTable")
                )
              )
            )
      ),
      tabItem(tabName = "aboutTab", icon=icon("info")
              
      )
  )
)

server <- function(input, output) { 
  
  # Tables for all domestic airlines (bullet point 1)
  
  output$ohareAirlinesTable <- DT::renderDataTable(ohareAirlines, server = TRUE, options = list(pageLength = 6, lengthChange = FALSE, searching = FALSE))
  output$midwayAirlinesTable <- DT::renderDataTable(midwayAirlines, server = TRUE, options = list(pageLength = 6, lengthChange = FALSE, searching = FALSE))
  
  # Charts for all domestic airlines (bullet point 1 cont.)
  output$ohareAirlinesDepartPie <- renderPlotly({
    plot_ly(ohareAirlines, labels = ~ohareAirlines$Carrier, values = ~ohareAirlines$Departures, type = "pie") %>%
      layout(xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
             yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
  })
  
  output$ohareAirlinesArrivePie <- renderPlotly({
    plot_ly(ohareAirlines, labels = ~ohareAirlines$Carrier, values = ~ohareAirlines$Arrivals, type = "pie") %>%
      layout(xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
             yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
  })
  
  output$midwayAirlinesDepartPie <- renderPlotly({
    plot_ly(midwayAirlines, labels = ~midwayAirlines$Carrier, values = ~midwayAirlines$Departures, type = "pie") %>%
      layout(xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
             yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
  })
  
  output$midwayAirlinesArrivePie <- renderPlotly({
    plot_ly(midwayAirlines, labels = ~midwayAirlines$Carrier, values = ~midwayAirlines$Arrivals, type = "pie") %>%
      layout(xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
             yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
  })
  
  # Tables for each day of the week for ohare and midway
  output$ohareDayDataTable <- DT::renderDataTable(ohareDayData, server = TRUE, options = list(pageLength = 7, lengthChange = FALSE, searching = FALSE))
  output$midwayDayDataTable <- DT::renderDataTable(midwayDayData, server = TRUE, options = list(pageLength = 7, lengthChange = FALSE, searching = FALSE))
  
}

shinyApp(ui, server)